In [17]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score , precision_score
from sklearn.model_selection import train_test_split

In [18]:
heart_data = pd.read_csv('heart.csv')
heart_data

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,57,0,0,140,241,0,1,123,1,0.2,1,0,3,0
299,45,1,3,110,264,0,1,132,0,1.2,1,0,3,0
300,68,1,0,144,193,1,1,141,0,3.4,1,2,3,0
301,57,1,0,130,131,0,1,115,1,1.2,1,1,3,0
302,57,0,1,130,236,0,0,174,0,0.0,1,1,2,0

In [19]:
X = heart_data.drop(['target'] , axis = 1)
y = heart_data['target']
X
y

0      1
1      1
2      1
3      1
4      1
      ..
298    0
299    0
300    0
301    0
302    0
Name: target, Length: 303, dtype: int64

In [20]:
X_train,X_test,y_train,y_test= train_test_split(X,y,random_state = 42 ,test_size = 0.2)
X_train

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal
132,42,1,1,120,295,0,1,162,0,0.0,2,0,2
202,58,1,0,150,270,0,0,111,1,0.8,2,0,3
196,46,1,2,150,231,0,1,147,0,3.6,1,0,2
75,55,0,1,135,250,0,0,161,0,1.4,1,0,2
176,60,1,0,117,230,1,1,160,1,1.4,2,2,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...
188,50,1,2,140,233,0,1,163,0,0.6,1,1,3
71,51,1,2,94,227,0,1,154,1,0.0,2,1,3
106,69,1,3,160,234,1,0,131,0,0.1,1,1,2
270,46,1,0,120,249,0,0,144,0,0.8,2,0,3
102,63,0,1,140,195,0,1,179,0,0.0,2,2,2

In [21]:
y_train[y_train==1].count()#133
y_train[y_train==0].count()#109

np.int64(109)

In [22]:

y_test[y_test==0].count()#29
y_test[y_test==1].count()#32

np.int64(32)

In [23]:
model = LogisticRegression(max_iter=2000)
model.fit(X_train,y_train)

LogisticRegression(max_iter=2000)

In [24]:
y_pred = model.predict(X_test)

In [25]:

accuracy = accuracy_score (y_pred,y_test)
precision = precision_score(y_pred , y_test)
print(accuracy)
print(precision)

0.8852459016393442
0.90625

In [26]:
# confusion matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_pred,y_test)
print(cm)

[[25  3]
 [ 4 29]]

In [27]:
# classification report
from sklearn.metrics import classification_report
cr = classification_report(y_pred,y_test)
print(cr)

              precision    recall  f1-score   support

           0       0.86      0.89      0.88        28
           1       0.91      0.88      0.89        33

    accuracy                           0.89        61
   macro avg       0.88      0.89      0.88        61
weighted avg       0.89      0.89      0.89        61

In [30]:
from sklearn.metrics import accuracy_score,precision_score,recall_score,f1_score
print('Accuracy',accuracy_score(y_test,y_pred))
print('Precision',precision_score(y_test,y_pred))
print('Recall',recall_score(y_test,y_pred))
print('F1 score',f1_score(y_test,y_pred))

Accuracy 0.8852459016393442
Precision 0.8787878787878788
Recall 0.90625
F1 score 0.8923076923076924

In [10]:
y_pred

array([0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0,
       0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0])

In [11]:
y_test

179    0
228    0
111    1
246    0
60     1
      ..
249    0
104    1
300    0
193    0
184    0
Name: target, Length: 61, dtype: int64

In [12]:
accuracy = accuracy_score (y_test,y_pred) * 100
precision = precision_score(y_test , y_pred) * 100
print(accuracy)
print(precision)

88.52459016393442
87.87878787878788

In [14]:
# standrazation 
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train =scaler.fit_transform(X_train)
X_train

array([[-1.35679832,  0.72250438,  0.00809909, ...,  0.95390513,
        -0.68970073, -0.50904773],
       [ 0.38508599,  0.72250438, -0.97189094, ...,  0.95390513,
        -0.68970073,  1.17848036],
       [-0.92132724,  0.72250438,  0.98808912, ..., -0.69498803,
        -0.68970073, -0.50904773],
       ...,
       [ 1.58263146,  0.72250438,  1.96807914, ..., -0.69498803,
         0.32186034, -0.50904773],
       [-0.92132724,  0.72250438, -0.97189094, ...,  0.95390513,
        -0.68970073,  1.17848036],
       [ 0.92942484, -1.38407465,  0.00809909, ...,  0.95390513,
         1.33342142, -0.50904773]])

In [15]:
X_test = scaler.transform(X_test)
X_test

array([[ 2.76218225e-01,  7.22504380e-01, -9.71890936e-01,
         1.16949120e+00,  5.53408401e-01, -3.83300706e-01,
        -1.04610909e+00, -1.70875171e+00,  1.47790748e+00,
        -3.75556294e-01, -6.94988026e-01,  3.21860343e-01,
        -2.19657581e+00],
       [ 4.93953764e-01,  7.22504380e-01,  1.96807914e+00,
         2.36038903e+00,  7.81171723e-01, -3.83300706e-01,
        -1.04610909e+00,  3.98288831e-01, -6.76632341e-01,
        -7.39094787e-01, -6.94988026e-01, -6.89700735e-01,
         1.17848036e+00],
       [ 2.76218225e-01,  7.22504380e-01,  9.88089118e-01,
         1.16949120e+00, -2.29363312e+00,  2.60891771e+00,
         8.43132697e-01,  1.02591793e+00, -6.76632341e-01,
        -7.39094787e-01,  9.53905134e-01,  3.21860343e-01,
         1.17848036e+00],
       [ 1.67350456e-01, -1.38407465e+00, -9.71890936e-01,
         2.16772932e-01,  3.07778522e+00, -3.83300706e-01,
        -1.04610909e+00, -5.18701733e-03,  1.47790748e+00,
         8.05943807e-01, -6.94988026e-01,  1.33342142e+00,
         1.17848036e+00],
       [ 1.80036700e+00, -1.38407465e+00,  9.88089118e-01,
        -1.21230447e+00,  3.44625356e-01,  2.60891771e+00,
        -1.04610909e+00, -9.01800013e-01, -6.76632341e-01,
        -9.20864033e-01,  9.53905134e-01,  3.21860343e-01,
        -5.09047728e-01],
       [ 2.76218225e-01,  7.22504380e-01,  9.88089118e-01,
         1.16949120e+00, -1.49646149e+00, -3.83300706e-01,
         8.43132697e-01,  1.07074858e+00, -6.76632341e-01,
         5.33289937e-01,  9.53905134e-01, -6.89700735e-01,
        -5.09047728e-01],
       [-9.21327240e-01, -1.38407465e+00, -9.71890936e-01,
         4.54952499e-01, -7.29407332e-02, -3.83300706e-01,
        -1.04610909e+00,  8.44742822e-02,  1.47790748e+00,
        -9.20864033e-01, -6.94988026e-01, -6.89700735e-01,
        -5.09047728e-01],
       [ 1.67350456e-01, -1.38407465e+00, -9.71890936e-01,
         4.14673578e+00,  7.81171723e-01,  2.60891771e+00,
        -1.04610909e+00, -7.67308064e-01,  1.47790748e+00,
         2.71452089e+00, -2.34388119e+00,  1.33342142e+00,
         1.17848036e+00],
       [-5.03850834e-02,  7.22504380e-01, -9.71890936e-01,
        -4.97765768e-01,  7.43211169e-01, -3.83300706e-01,
        -1.04610909e+00, -1.52942911e+00,  1.47790748e+00,
         1.98744391e+00, -6.94988026e-01,  1.33342142e+00,
        -5.09047728e-01],
       [-5.03850834e-02,  7.22504380e-01,  9.88089118e-01,
        -3.19131093e-01,  4.96467571e-01, -3.83300706e-01,
        -1.04610909e+00,  8.44742822e-02, -6.76632341e-01,
        -4.66440917e-01, -2.34388119e+00,  3.21860343e-01,
        -5.09047728e-01],
       [ 2.76218225e-01,  7.22504380e-01, -9.71890936e-01,
         5.74042282e-01, -1.04093485e+00, -3.83300706e-01,
         8.43132697e-01, -9.48483169e-02, -6.76632341e-01,
        -5.57325540e-01, -6.94988026e-01, -6.89700735e-01,
        -2.19657581e+00],
       [ 4.93953764e-01,  7.22504380e-01,  1.96807914e+00,
         2.83674817e+00,  4.39526740e-01, -3.83300706e-01,
        -1.04610909e+00, -2.29340266e-01, -6.76632341e-01,
         2.89629014e+00, -2.34388119e+00, -6.89700735e-01,
         1.17848036e+00],
       [-2.68120623e-01,  7.22504380e-01,  8.09909113e-03,
        -6.16855552e-01,  1.48344196e+00, -3.83300706e-01,
         8.43132697e-01,  9.81087278e-01, -6.76632341e-01,
        -7.39094787e-01,  9.53905134e-01, -6.89700735e-01,
        -5.09047728e-01],
       [-1.57453386e+00,  7.22504380e-01, -9.71890936e-01,
        -1.21230447e+00, -1.51544177e+00, -3.83300706e-01,
        -1.04610909e+00, -1.61909041e+00,  1.47790748e+00,
         8.96828430e-01, -6.94988026e-01, -6.89700735e-01,
         1.17848036e+00],
       [-9.21327240e-01, -1.38407465e+00,  8.09909113e-03,
        -1.51002893e+00, -8.13171528e-01, -3.83300706e-01,
         8.43132697e-01,  9.81087278e-01, -6.76632341e-01,
        -9.20864033e-01,  9.53905134e-01, -6.89700735e-01,
        -5.09047728e-01],
       [-1.13906278e+00,  7.22504380e-01,  9.88089118e-01,
         5.74042282e-01, -2.24782948e-01, -3.83300706e-01,
        -1.04610909e+00,  1.33973248e+00, -6.76632341e-01,
        -9.20864033e-01,  9.53905134e-01, -6.89700735e-01,
        -5.09047728e-01],
       [-2.22774047e+00, -1.38407465e+00,  8.09909113e-03,
        -7.35945335e-01, -6.99289868e-01, -3.83300706e-01,
         8.43132697e-01,  1.87770027e+00, -6.76632341e-01,
        -2.84671671e-01,  9.53905134e-01, -6.89700735e-01,
        -5.09047728e-01],
       [-5.03850834e-02,  7.22504380e-01, -9.71890936e-01,
        -6.16855552e-01, -1.11685596e+00, -3.83300706e-01,
         8.43132697e-01, -1.66392106e+00, -6.76632341e-01,
         3.51520691e-01, -6.94988026e-01,  3.21860343e-01,
         1.17848036e+00],
       [-9.21327240e-01,  7.22504380e-01, -9.71890936e-01,
         5.74042282e-01,  1.21771809e+00, -3.83300706e-01,
         8.43132697e-01, -1.35010651e+00,  1.47790748e+00,
         7.15059184e-01, -6.94988026e-01,  1.33342142e+00,
         1.17848036e+00],
       [ 7.11689304e-01,  7.22504380e-01, -9.71890936e-01,
         4.54952499e-01, -1.53442205e+00, -3.83300706e-01,
        -1.04610909e+00, -1.12595326e+00,  1.47790748e+00,
         2.35098240e+00, -6.94988026e-01,  3.21860343e-01,
        -5.09047728e-01],
       [ 1.03829261e+00,  7.22504380e-01,  1.96807914e+00,
         2.36038903e+00, -3.76625162e-01, -3.83300706e-01,
        -1.04610909e+00,  2.18966232e-01, -6.76632341e-01,
        -3.75556294e-01, -6.94988026e-01, -6.89700735e-01,
         1.17848036e+00],
       [ 1.67350456e-01,  7.22504380e-01, -9.71890936e-01,
        -2.14066346e-02,  6.86270339e-01,  2.60891771e+00,
        -1.04610909e+00, -2.11222756e+00,  1.47790748e+00,
         5.33289937e-01, -2.34388119e+00, -6.89700735e-01,
         1.17848036e+00],
       [ 1.36489592e+00,  7.22504380e-01, -9.71890936e-01,
        -6.16855552e-01, -1.86822394e-01, -3.83300706e-01,
         8.43132697e-01, -3.54680835e+00, -6.76632341e-01,
        -1.20178014e-02, -6.94988026e-01, -6.89700735e-01,
        -5.09047728e-01],
       [ 1.80036700e+00, -1.38407465e+00,  8.09909113e-03,
         1.76494012e+00,  1.04689560e+00, -3.83300706e-01,
         8.43132697e-01,  5.32780780e-01, -6.76632341e-01,
        -5.57325540e-01,  9.53905134e-01,  1.33342142e+00,
        -5.09047728e-01],
       [-1.13906278e+00, -1.38407465e+00,  9.88089118e-01,
        -7.35945335e-01, -9.19210100e-02, -3.83300706e-01,
         8.43132697e-01, -5.00176671e-02, -6.76632341e-01,
        -6.48210163e-01, -6.94988026e-01,  3.21860343e-01,
        -5.09047728e-01],
       [-1.57453386e+00,  7.22504380e-01, -9.71890936e-01,
         1.28858098e+00, -4.52546269e-01, -3.83300706e-01,
         8.43132697e-01,  1.38456313e+00, -6.76632341e-01,
        -9.20864033e-01,  9.53905134e-01, -6.89700735e-01,
         1.17848036e+00],
       [ 4.93953764e-01,  7.22504380e-01,  1.96807914e+00,
         1.76494012e+00,  4.96467571e-01, -3.83300706e-01,
        -1.04610909e+00, -1.12595326e+00, -6.76632341e-01,
        -9.20864033e-01,  9.53905134e-01, -6.89700735e-01,
        -5.09047728e-01],
       [-3.76988392e-01,  7.22504380e-01, -9.71890936e-01,
         5.74042282e-01,  2.68704249e-01, -3.83300706e-01,
        -1.04610909e+00,  1.60871637e+00,  1.47790748e+00,
        -9.20864033e-01,  9.53905134e-01, -6.89700735e-01,
        -5.09047728e-01],
       [ 2.76218225e-01,  7.22504380e-01, -9.71890936e-01,
         2.06266458e+00,  8.00152000e-01,  2.60891771e+00,
        -1.04610909e+00, -1.17078391e+00, -6.76632341e-01,
        -1.20178014e-02, -6.94988026e-01,  2.34498250e+00,
         1.17848036e+00],
       [-4.85856162e-01, -1.38407465e+00, -9.71890936e-01,
        -1.21230447e+00,  1.35842312e-01, -3.83300706e-01,
        -1.04610909e+00,  3.98288831e-01, -6.76632341e-01,
        -9.20864033e-01,  9.53905134e-01, -6.89700735e-01,
        -5.09047728e-01],
       [ 1.03829261e+00,  7.22504380e-01, -9.71890936e-01,
        -1.40496418e-01,  3.06664803e-01, -3.83300706e-01,
         8.43132697e-01, -2.02256626e+00,  1.47790748e+00,
        -7.39094787e-01, -6.94988026e-01,  3.21860343e-01,
         1.17848036e+00],
       [ 7.11689304e-01,  7.22504380e-01, -9.71890936e-01,
         5.74042282e-01, -7.56230698e-01, -3.83300706e-01,
        -1.04610909e+00, -5.43154815e-01,  1.47790748e+00,
         8.05943807e-01,  9.53905134e-01,  3.21860343e-01,
         1.17848036e+00],
       [ 8.20557073e-01,  7.22504380e-01, -9.71890936e-01,
        -6.16855552e-01,  3.82585910e-01, -3.83300706e-01,
         8.43132697e-01, -2.29155016e+00,  1.47790748e+00,
         7.15059184e-01, -6.94988026e-01,  1.33342142e+00,
         1.17848036e+00],
       [-1.03019501e+00,  7.22504380e-01, -9.71890936e-01,
        -1.56957382e+00, -7.37250421e-01, -3.83300706e-01,
        -1.04610909e+00, -9.48483169e-02,  1.47790748e+00,
         1.80567466e+00, -6.94988026e-01, -6.89700735e-01,
        -5.09047728e-01],
       [ 1.25602815e+00, -1.38407465e+00,  1.96807914e+00,
         1.16949120e+00, -3.95605439e-01, -3.83300706e-01,
         8.43132697e-01, -1.61909041e+00, -6.76632341e-01,
         1.44213617e+00, -2.34388119e+00, -6.89700735e-01,
        -5.09047728e-01],
       [ 9.29424843e-01,  7.22504380e-01, -9.71890936e-01,
        -2.14066346e-02,  1.35842312e-01, -3.83300706e-01,
        -1.04610909e+00, -1.39678967e-01, -6.76632341e-01,
         3.51520691e-01, -6.94988026e-01,  3.21860343e-01,
         1.17848036e+00],
       [-3.76988392e-01,  7.22504380e-01,  9.88089118e-01,
        -3.19131093e-01, -3.49801796e-02,  2.60891771e+00,
        -1.04610909e+00,  7.12103379e-01, -6.76632341e-01,
         1.26036692e+00, -6.94988026e-01, -6.89700735e-01,
        -5.09047728e-01],
       [-7.03591701e-01,  7.22504380e-01,  9.88089118e-01,
        -3.78675985e-01,  1.54822588e-01,  2.60891771e+00,
         8.43132697e-01,  1.11557923e+00, -6.76632341e-01,
        -9.20864033e-01,  9.53905134e-01,  1.33342142e+00,
        -5.09047728e-01],
       [-1.57453386e+00,  7.22504380e-01,  1.96807914e+00,
         5.74042282e-01, -9.08072912e-01, -3.83300706e-01,
         8.43132697e-01,  1.25007118e+00,  1.47790748e+00,
         3.51520691e-01,  9.53905134e-01, -6.89700735e-01,
         1.17848036e+00],
       [-1.03019501e+00,  7.22504380e-01, -9.71890936e-01,
        -9.14580010e-01,  2.49723972e-01, -3.83300706e-01,
        -1.04610909e+00,  1.56388572e+00, -6.76632341e-01,
        -9.20864033e-01,  9.53905134e-01, -6.89700735e-01,
        -5.09047728e-01],
       [-2.68120623e-01,  7.22504380e-01,  9.88089118e-01,
         4.54952499e-01, -4.52546269e-01, -3.83300706e-01,
         8.43132697e-01,  8.46595328e-01, -6.76632341e-01,
        -9.20864033e-01,  9.53905134e-01,  3.35654358e+00,
        -5.09047728e-01],
       [ 4.93953764e-01,  7.22504380e-01,  8.09909113e-03,
         5.74042282e-01, -4.90506823e-01, -3.83300706e-01,
         8.43132697e-01,  6.22442080e-01,  1.47790748e+00,
        -9.20864033e-01,  9.53905134e-01, -6.89700735e-01,
        -5.09047728e-01],
       [ 8.20557073e-01,  7.22504380e-01,  8.09909113e-03,
        -1.40496418e-01, -7.37250421e-01,  2.60891771e+00,
        -1.04610909e+00, -4.53493515e-01, -6.76632341e-01,
        -9.20864033e-01,  9.53905134e-01, -6.89700735e-01,
        -5.09047728e-01],
       [-1.46566609e+00,  7.22504380e-01,  9.88089118e-01,
        -2.14066346e-02, -6.23368760e-01, -3.83300706e-01,
        -1.04610909e+00,  8.01764679e-01, -6.76632341e-01,
         8.96828430e-01, -6.94988026e-01, -6.89700735e-01,
        -5.09047728e-01],
       [-1.13906278e+00,  7.22504380e-01,  8.09909113e-03,
        -6.16855552e-01,  3.06664803e-01, -3.83300706e-01,
         8.43132697e-01,  1.02591793e+00, -6.76632341e-01,
        -9.20864033e-01,  9.53905134e-01, -6.89700735e-01,
         1.17848036e+00],
       [-1.24793055e+00,  7.22504380e-01, -9.71890936e-01,
         9.76831488e-02,  2.98037404e-03,  2.60891771e+00,
        -1.04610909e+00, -3.19001566e-01,  1.47790748e+00,
        -8.29979410e-01, -6.94988026e-01,  3.35654358e+00,
         1.17848036e+00],
       [-2.68120623e-01,  7.22504380e-01, -9.71890936e-01,
        -1.40496418e-01, -8.13171528e-01,  2.60891771e+00,
         8.43132697e-01,  2.63796881e-01,  1.47790748e+00,
        -1.20178014e-02, -6.94988026e-01, -6.89700735e-01,
        -3.88410390e+00],
       [-2.68120623e-01,  7.22504380e-01,  8.09909113e-03,
        -1.40496418e-01, -7.94191252e-01,  2.60891771e+00,
         8.43132697e-01,  1.51905508e+00, -6.76632341e-01,
        -9.20864033e-01,  9.53905134e-01, -6.89700735e-01,
        -5.09047728e-01],
       [ 3.85085995e-01, -1.38407465e+00, -9.71890936e-01,
         2.36038903e+00, -4.14585716e-01,  2.60891771e+00,
        -1.04610909e+00, -1.84509616e-01,  1.47790748e+00,
         1.62390542e+00, -6.94988026e-01,  1.33342142e+00,
        -2.19657581e+00],
       [ 5.84826861e-02,  7.22504380e-01, -9.71890936e-01,
         1.76494012e+00,  8.00152000e-01, -3.83300706e-01,
        -1.04610909e+00, -2.29340266e-01,  1.47790748e+00,
        -1.93787048e-01, -6.94988026e-01,  3.21860343e-01,
         1.17848036e+00],
       [-7.03591701e-01,  7.22504380e-01, -9.71890936e-01,
        -2.14066346e-02,  1.73802865e-01,  2.60891771e+00,
        -1.04610909e+00, -5.18701733e-03,  1.47790748e+00,
        -9.20864033e-01,  9.53905134e-01,  1.33342142e+00,
         1.17848036e+00],
       [-1.03019501e+00,  7.22504380e-01, -9.71890936e-01,
         6.93132066e-01,  1.17975754e+00, -3.83300706e-01,
        -1.04610909e+00, -1.39678967e-01,  1.47790748e+00,
        -9.20864033e-01, -6.94988026e-01,  2.34498250e+00,
         1.17848036e+00],
       [-1.46566609e+00,  7.22504380e-01,  8.09909113e-03,
         2.76317824e-01, -8.32151805e-01, -3.83300706e-01,
         8.43132697e-01, -8.12138713e-01, -6.76632341e-01,
        -9.20864033e-01, -6.94988026e-01, -6.89700735e-01,
        -2.19657581e+00],
       [ 6.02821534e-01, -1.38407465e+00,  9.88089118e-01,
        -1.68866360e+00,  1.35058003e+00, -3.83300706e-01,
         8.43132697e-01,  4.43119480e-01, -6.76632341e-01,
        -9.20864033e-01,  9.53905134e-01,  3.21860343e-01,
        -5.09047728e-01],
       [ 3.85085995e-01,  7.22504380e-01, -9.71890936e-01,
        -3.19131093e-01,  1.00893504e+00, -3.83300706e-01,
        -1.04610909e+00,  9.36256628e-01, -6.76632341e-01,
        -9.20864033e-01,  9.53905134e-01,  1.33342142e+00,
         1.17848036e+00],
       [ 8.20557073e-01, -1.38407465e+00, -9.71890936e-01,
         1.76494012e+00, -1.57238260e+00, -3.83300706e-01,
        -1.04610909e+00, -2.29340266e-01, -6.76632341e-01,
         4.71398260e+00, -2.34388119e+00,  2.34498250e+00,
         1.17848036e+00],
       [ 1.58263146e+00,  7.22504380e-01,  9.88089118e-01,
         5.74042282e-01,  1.35842312e-01, -3.83300706e-01,
        -1.04610909e+00, -1.84509616e-01, -6.76632341e-01,
         8.96828430e-01, -6.94988026e-01,  2.34498250e+00,
         1.17848036e+00],
       [-4.85856162e-01,  7.22504380e-01,  9.88089118e-01,
        -8.09515263e-02, -9.65013743e-01, -3.83300706e-01,
         8.43132697e-01,  5.77611430e-01, -6.76632341e-01,
        -9.20864033e-01,  9.53905134e-01, -6.89700735e-01,
        -5.09047728e-01],
       [ 1.47376369e+00,  7.22504380e-01, -9.71890936e-01,
         8.12221849e-01, -1.02195457e+00,  2.60891771e+00,
         8.43132697e-01, -4.08662865e-01, -6.76632341e-01,
         2.16921315e+00, -6.94988026e-01,  1.33342142e+00,
         1.17848036e+00],
       [ 6.02821534e-01,  7.22504380e-01, -9.71890936e-01,
         8.71766741e-01,  6.67290062e-01, -3.83300706e-01,
        -1.04610909e+00, -3.63832216e-01,  1.47790748e+00,
         1.62390542e+00, -6.94988026e-01,  1.33342142e+00,
         1.17848036e+00],
       [-4.85856162e-01,  7.22504380e-01, -9.71890936e-01,
         1.16949120e+00, -7.29407332e-02, -3.83300706e-01,
        -1.04610909e+00, -9.91461312e-01, -6.76632341e-01,
         1.44213617e+00, -6.94988026e-01, -6.89700735e-01,
         1.17848036e+00]])

In [16]:
model = LogisticRegression(max_iter=2000)
model.fit(X_train,y_train)
y_pred = model.predict(X_test)

accuracy = accuracy_score (y_pred,y_test)
precision = precision_score(y_pred , y_test)
print(accuracy)
print(precision)

0.8524590163934426
0.84375